config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :articles
  post 'search', to: 'search#index', as: :search
  post 'search/suggestions', to: 'search#suggestions', as: :search_suggestions
  get 'recent_searches_by_user', to: 'search#recent_searches_by_user', as: :recent_searches_by_user
  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    searchkick text_middle: %i[title, body]
end

app/models/search.rb
class Search < ApplicationRecord
    belongs_to :user
  
    validates :query, presence: true, length: { minimum: 5, maximum: 100 }
  
    scope :latest_search, -> (user) { where(user: user).order(created_at: :desc).limit(1).first }
  end
  

app/models/user.rb
class User < ApplicationRecord
    searchkick
    has_many :searches

    validates :user_ip, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_turbo_frame
    helper_method :current_user 
  
    protected
  
    def set_turbo_frame
      request.variant = :turbo_frame if turbo_frame_request?
    end
  
    def current_user
      @current_user ||= User.find_or_create_by(user_ip: request.remote_ip)
    end
  end
  

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
      @results = search_for_articles
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('articles', partial: 'articles/articles', locals: { articles: @results })
        end
      end
        search_create if query_param.length >= 2
    end

    def suggestions
      @results = search_for_articles
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('articles', partial: 'search/suggestions', locals: { results: @results })
        end
      end
    end

    def recent_searches_by_user
    end    

    private

    def search_create
      latest_search_record = latest_search
    
      if latest_search_record.nil? || !matched_articles(latest_search_record.query, query_param)
        Search.create(query: query_param.strip, user: current_user)
      else
        latest_search_record.update(query: query_param)
      end
    end
    
    def latest_search
      @latest_search ||= Search.latest_search(current_user)
    end

    def query_param
      params[:query]&.strip
    end

    def matched_articles(str1, str2)
      winkler = Amatch::JaroWinkler.new(str1)
      similarity_distance = winkler.match(str2)
      similarity_distance > 0.7
    end
    
    def search_for_articles
      if params[:query].blank?
        Article.all
      else
        Article.search(params[:query], fields: %i[title, body], operator: "or", match: :text_middle)
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="card mt-3">
  <div class="card-body">
    <p class="my-4">
      <strong class="block font-weight-medium mb-1">Title:</strong>
      <%= article.title %>
    </p>

    <p class="my-4">
      <strong class="block font-weight-medium mb-1">Body:</strong>
      <%= article.body %>
    </p>

    <% if action_name != "show" %>
      <%= link_to "Show this article", article, class: "btn btn-outline-secondary btn-sm rounded-lg font-weight-medium" %>
      <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-outline-secondary btn-sm rounded-lg ml-2 font-weight-medium" %>
      <hr class="my-4">
    <% end %>
  </div>
</div>

app/views/articles/_articles.html.erb
<% articles.each do |article| %>
  <div class="card mt-3">
    <div class="card-body">
      <%= render article %>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :body %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="font-weight-bold fs-4">Editing article</h1>

      <%= render "form", article: @article %>

      <div class="mt-2">
        <%= link_to "Show this article", @article, class: "btn btn-outline-secondary rounded-lg" %>
        <%= link_to "Back to articles", articles_path, class: "btn btn-outline-secondary ml-2" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container mt-5">
  <% if notice.present? %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <div>
    <%= render partial: "search/form", locals: { results: [] } %>
  </div>

  <div class="d-flex justify-content-between align-items-center mt-3">
    <h1 class="font-weight-bold fs-4">Articles</h1>
    <div>
    <%= link_to "Resent user searches", recent_searches_by_user_path,  class: "btn btn-secondary" %>
    <%= link_to "New article", new_article_path, class: "btn btn-primary" %>
    </div>
  </div>
  
  <div id="articles" class="min-w-full mt-3">
    <%= render 'articles/articles', articles: @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-body">
          <h1 class="font-weight-bold fs-4 mb-4">New Article</h1>
          <%= render "form", article: @article %>
          <div class="mt-3">
            <%= link_to "Back to Articles", articles_path, class: "btn btn-outline-secondary rounded-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% if notice.present? %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>

      <%= render @article %>

      <div class="mt-2">
        <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-outline-secondary rounded-lg" %>
        <%= button_to "Destroy this article", article_path(@article), method: :delete, class: "btn btn-outline-secondary ml-2" %>
        <%= link_to "Back to articles", articles_path, class: "btn btn-outline-secondary ml-2" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngineAnalytices</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/search/_form.html.erb
<%= form_with(url: search_path, method: :post, data: { controller: "search", action: "keyup->search#suggestions", suggestions_url: search_suggestions_path }) do |form| %>
  <div class="container mt-4">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="input-group">
          <%= form.text_field :query, autocomplete: :off, data: { search_target: 'input', action: "blur->search#hideSuggestions" }, placeholder: 'Search...', class: 'form-control' %>
        </div>
        <div class="mt-3">
          <h3><span>Trends:</span> AI, SpaceX, Amazon.</h3>
        </div>
        <div id="suggestion" data-search-target="suggestions" data-action="mousedown->search#childClicked" class="position-absolute w-100 mt-2">
          <%= render partial: "search/suggestions", locals: { results: results } %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
    <div>
    <% results.each do |article|%>
        <div>
            <%= link_to article.title, article %>
        </div>
    <% end %>
    </div>
<% end %>

app/views/search/recent_searches_by_user.html.erb
<% if current_user %>
  <div class="container mt-4">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">Recent Searches by <%= current_user.user_ip %>:</h3>
        <ul class="list-group list-group-flush">
          <% current_user.searches.order(created_at: :desc).limit(5).each do |search| %>
            <li class="list-group-item recent-search-item"><%= search.query %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>